version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo123
    ports:
      - "3307:3306"         # host:container (optional - use 3307 on host)
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: spring-mvc-mysql-demo-docker
    restart: always
    depends_on:
      - db
    ports:
      - "8085:8080"         # host:container â†’ access on http://localhost:8081
    # If you later want to use env vars for DB, you can add environment: here

volumes:
  db_data:

