apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mvc-app
  template:
    metadata:
      labels:
        app: spring-mvc-app
    spec:
      containers:
        - name: spring-mvc-app
          image: spring-mvc-mysql-demo-k8s:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-app-service
spec:
  selector:
    app: spring-mvc-app
  type: NodePort
  ports:
    - port: 8080        # service port inside cluster
      targetPort: 8080  # container port
      nodePort: 30080   # host port via NodePort (kind exposes this)

